# 과제3
* Memory store로 Recommender system 만들기
1) content-base
2) user-base

In [36]:
import pandas as pd
import numpy as np
from ast import literal_eval
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

from dataclasses import dataclass

from langchain.agents import create_agent
from langchain.tools import tool, ToolRuntime
from langgraph.store.memory import InMemoryStore

## 1) Content-base Recommender

### prep

In [45]:
orig_df = pd.read_csv('./data/tmdb_5000_movies.csv')
df = orig_df.copy()

df.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [46]:
df.info()               # 데이터에 대한 대략적인 정보 보기

<class 'pandas.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   str
 2   homepage              1712 non-null   str
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   str
 5   original_language     4803 non-null   str
 6   original_title        4803 non-null   str
 7   overview              4800 non-null   str
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   str
 10  production_countries  4803 non-null   str
 11  release_date          4802 non-null   str
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   str
 15  status                4803 non-null   str
 16  tagline               3959 non-null   str
 17  title                 4803 non-null   str
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), str(13)
memory usage: 750.6 KB

In [47]:
df.iloc[0]["keywords"]        # 어떤 데이터가 들어있는지 확인하기 위해 찍어봄. str데이터인걸 확인

'[{"id": 1463, "name": "culture clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "space war"}, {"id": 3388, "name": "space colony"}, {"id": 3679, "name": "society"}, {"id": 3801, "name": "space travel"}, {"id": 9685, "name": "futuristic"}, {"id": 9840, "name": "romance"}, {"id": 9882, "name": "space"}, {"id": 9951, "name": "alien"}, {"id": 10148, "name": "tribe"}, {"id": 10158, "name": "alien planet"}, {"id": 10987, "name": "cgi"}, {"id": 11399, "name": "marine"}, {"id": 13065, "name": "soldier"}, {"id": 14643, "name": "battle"}, {"id": 14720, "name": "love affair"}, {"id": 165431, "name": "anti war"}, {"id": 193554, "name": "power relations"}, {"id": 206690, "name": "mind and soul"}, {"id": 209714, "name": "3d"}]'

In [48]:
from ast import literal_eval

result = literal_eval(df.iloc[0]["keywords"])     # str인 다른 데이터를 바로 사용할 수 있는 원래 데이터로 바꿔줌.
result

[{'id': 1463, 'name': 'culture clash'},
 {'id': 2964, 'name': 'future'},
 {'id': 3386, 'name': 'space war'},
 {'id': 3388, 'name': 'space colony'},
 {'id': 3679, 'name': 'society'},
 {'id': 3801, 'name': 'space travel'},
 {'id': 9685, 'name': 'futuristic'},
 {'id': 9840, 'name': 'romance'},
 {'id': 9882, 'name': 'space'},
 {'id': 9951, 'name': 'alien'},
 {'id': 10148, 'name': 'tribe'},
 {'id': 10158, 'name': 'alien planet'},
 {'id': 10987, 'name': 'cgi'},
 {'id': 11399, 'name': 'marine'},
 {'id': 13065, 'name': 'soldier'},
 {'id': 14643, 'name': 'battle'},
 {'id': 14720, 'name': 'love affair'},
 {'id': 165431, 'name': 'anti war'},
 {'id': 193554, 'name': 'power relations'},
 {'id': 206690, 'name': 'mind and soul'},
 {'id': 209714, 'name': '3d'}]

In [49]:
df["keywords"] = orig_df["keywords"].apply(literal_eval)  # 이렇게 해야 pandas 내부 함수이기 때문에 for문보다 훨씬 빠름

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   str
 2   homepage              1712 non-null   str
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   str
 6   original_title        4803 non-null   str
 7   overview              4800 non-null   str
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   str
 10  production_countries  4803 non-null   str
 11  release_date          4802 non-null   str
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   str
 15  status                4803 non-null   str
 16  tagline               3959 non-null   str
 17  title                 4803 non-null   str
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), object(1), str(12)
memory usage: 750.6+ KB

In [50]:
# 구조 파악하기
data_list = []

for i in df.iloc[0,:]['keywords']:
    data_list.append(i['name'])

data_list

['culture clash',
 'future',
 'space war',
 'space colony',
 'society',
 'space travel',
 'futuristic',
 'romance',
 'space',
 'alien',
 'tribe',
 'alien planet',
 'cgi',
 'marine',
 'soldier',
 'battle',
 'love affair',
 'anti war',
 'power relations',
 'mind and soul',
 '3d']

In [51]:
# 장르 리스트화
df['keywords'] = df['keywords'].apply(
    lambda lst: [x['name'] for x in lst]
)

df['keywords'].head()

0    [culture clash, future, space war, space colon...
1    [ocean, drug abuse, exotic island, east india ...
2    [spy, based on novel, secret agent, sequel, mi...
3    [dc comics, crime fighter, terrorist, secret i...
4    [based on novel, mars, medallion, space travel...
Name: keywords, dtype: object

In [53]:
# SF와 같은 띄어쓰기로 되어있는 데이터 붙이기.
df["keywords"] = df["keywords"].apply(
    lambda genre_list: [''.join(g.split()) for g in genre_list]
)

df["keywords"].head()

0    [cultureclash, future, spacewar, spacecolony, ...
1    [ocean, drugabuse, exoticisland, eastindiatrad...
2    [spy, basedonnovel, secretagent, sequel, mi6, ...
3    [dccomics, crimefighter, terrorist, secretiden...
4    [basedonnovel, mars, medallion, spacetravel, p...
Name: keywords, dtype: object

In [54]:
# CountVectorizer에 넣을 수 있게 prep하기.
df["keywords"] = df["keywords"].apply(
    lambda genre_list: ' '.join(genre_list)
)

df["keywords"].head()

0    cultureclash future spacewar spacecolony socie...
1    ocean drugabuse exoticisland eastindiatradingc...
2    spy basedonnovel secretagent sequel mi6 britis...
3    dccomics crimefighter terrorist secretidentity...
4    basedonnovel mars medallion spacetravel prince...
Name: keywords, dtype: str

In [55]:
from sklearn.feature_extraction.text import CountVectorizer

# CountVectorizer 모델 준비 - 단어사전을 만들고 등장한 단어 개수를 counting해준다.
count_vec = CountVectorizer(
    min_df=1, ngram_range=(1,1)
)

# 학습하여 변환 적용
genre_mat = count_vec.fit_transform(df["keywords"])

In [56]:
# 벡터라이저의 단어사전 확인하기 - 인덱스의 순서는 단어의 alphabetical order. 알파벳순
count_vec.vocabulary_

{'cultureclash': 2142,
 'future': 3459,
 'spacewar': 8197,
 'spacecolony': 8181,
 'society': 8112,
 'spacetravel': 8196,
 'futuristic': 3463,
 'romance': 7396,
 'space': 8176,
 'alien': 153,
 'tribe': 9084,
 'alienplanet': 166,
 'cgi': 1484,
 'marine': 5262,
 'soldier': 8127,
 'battle': 715,
 'loveaffair': 5096,
 'antiwar': 321,
 'powerrelations': 6766,
 'mindandsoul': 5514,
 '3d': 21,
 'ocean': 6115,
 'drugabuse': 2594,
 'exoticisland': 2927,
 'eastindiatradingcompany': 2677,
 'loveofone': 5106,
 'slife': 8028,
 'traitor': 9026,
 'shipwreck': 7865,
 'strongwoman': 8456,
 'ship': 7862,
 'alliance': 181,
 'calypso': 1285,
 'afterlife': 95,
 'fighter': 3201,
 'pirate': 6554,
 'swashbuckler': 8604,
 'aftercreditsstinger': 94,
 'spy': 8283,
 'basedonnovel': 677,
 'secretagent': 7685,
 'sequel': 7754,
 'mi6': 5455,
 'britishsecretservice': 1123,
 'unitedkingdom': 9238,
 'dccomics': 2236,
 'crimefighter': 2066,
 'terrorist': 8804,
 'secretidentity': 7694,
 'burglar': 1212,
 'hostagedrama': 4153,
 'timebomb': 8904,
 'gothamcity': 3705,
 'vigilante': 9366,
 'cover': 2024,
 'up': 9260,
 'superhero': 8535,
 'villainess': 9375,
 'tragichero': 9008,
 'terrorism': 8803,
 'destruction': 2377,
 'catwoman': 1446,
 'catburglar': 1424,
 'imax': 4287,
 'flood': 3309,
 'criminalunderworld': 2081,
 'batman': 711,
 'mars': 5282,
 'medallion': 5356,
 'princess': 6836,
 'steampunk': 8351,
 'martian': 5291,
 'escape': 2836,
 'edgarriceburroughs': 2700,
 'alienrace': 169,
 'superhumanstrength': 8541,
 'marscivilization': 5283,
 'swordandplanet': 8634,
 '19thcentury': 15,
 'dualidentity': 2628,
 'amnesia': 235,
 'sandstorm': 7535,
 'forgiveness': 3362,
 'spider': 8235,
 'wretch': 9714,
 'deathofafriend': 2270,
 'egomania': 2709,
 'sand': 7531,
 'narcism': 5853,
 'hostility': 4160,
 'marvelcomic': 5296,
 'revenge': 7292,
 'hostage': 4152,
 'magic': 5166,
 'horse': 4140,
 'fairytale': 3013,
 'musical': 5786,
 'animation': 290,
 'tower': 8979,
 'blondewoman': 935,
 'selfishness': 7728,
 'healingpower': 3933,
 'basedonfairytale': 671,
 'duringcreditsstinger': 2648,
 'healinggift': 3932,
 'animalsidekick': 282,
 'basedoncomicbook': 669,
 'vision': 9397,
 'superheroteam': 8539,
 'marvelcinematicuniverse': 5295,
 'witch': 9634,
 'broom': 1153,
 'schoolofwitchcraft': 7617,
 'wizardry': 9647,
 'apparition': 338,
 'teenagecrush': 8737,
 'werewolf': 9548,
 'superpowers': 8552,
 'clarkkent': 1693,
 'brucewayne': 1164,
 'dcextendeduniverse': 2237,
 'savingtheworld': 7574,
 'invulnerability': 4468,
 'kryptonite': 4765,
 'lexluthor': 4909,
 'killing': 4722,
 'undercover': 9206,
 'fortuneteller': 3374,
 'bondage': 1008,
 'monster': 5641,
 'captain': 1337,
 'cardgame': 1353,
 'compass': 1846,
 'daughter': 2227,
 'texas': 8818,
 'survivor': 8585,
 'texasranger': 8819,
 'partner': 6363,
 'outlaw': 6239,
 'lawyer': 4858,
 'train': 9014,
 'loneranger': 5025,
 'comanche': 1804,
 'theloneranger': 8848,
 'tonto': 8939,
 'superhuman': 8540,
 'alieninvasion': 162,
 'reboot': 7111,
 'fictionalplace': 3193,
 'brothersisterrelationship': 1160,
 'lion': 4965,
 'humanbeing': 4191,
 'leapintime': 4863,
 'matteroflifeanddeath': 5336,
 'faith': 3014,
 'uncle': 9198,
 'narnia': 5861,
 'fantasyworld': 3080,
 'newyork': 5985,
 'shield': 7858,
 'sea': 7663,
 'mutiny': 5820,
 'sword': 8633,
 'primeminister': 6830,
 'sailing': 7504,
 'silver': 7949,
 'duke': 2641,
 'mermaid': 5423,
 'timetravel': 8913,
 'timemachine': 8908,
 'fictionalgovernmentagency': 3189,
 'seeingthefuture': 7716,
 'changinghistory': 1506,
 'corruption': 1977,
 'elves': 2748,
 'dwarves': 2653,
 'orcs': 6206,
 'middle': 5465,
 'earth': 2667,
 'tolkien': 8932,
 'hobbit': 4072,
 'dragon': 2558,
 'unlikelyfriendship': 9244,
 'epicbattle': 2818,
 'swordandsorcery': 8636,
 'lossoffather': 5059,
 'serum': 7764,
 'scientificexperiment': 7630,
 'spiderbite': 8236,
 'maskedvigilante': 5308,
 'geneticengineering': 3552,
 'socialoutcast': 8106,
 'robinhood': 7358,
 'archer': 366,
 'knight': 4749,
 'sherwoodforest': 7857,
 'bowandarrow': 1047,
 'middleages': 5469,
 'medieval': 5372,
 'kingofengland': 4732,
 'wizard': 9645,
 'england': 2793,
 'experiment': 2936,
 'lordship': 5041,
 'polarbear': 6634,
 'orphan': 6224,
 'animal': 269,
 'basedonyoungadultnovel': 691,
 'filmbusiness': 3213,
 'screenplay': 7646,
 'showbusiness': 7911,
 'filmmaking': 3227,
 'filmproducer': 3229,
 'indigenous': 4340,
 'dinosaur': 2419,
 'iceberg': 4243,
 'panic': 6299,
 'titanic': 8918,
 'oceanliner': 6117,
 'epic': 2817,
 'richwoman': 7319,
 'poorman': 6708,
 'love': 5095,
 'disaster': 2435,
 'tragiclove': 9009,
 'classdifferences': 1696,
 'starcrossedlovers': 8327,
 'steerage': 8355,
 'salvage': 7522,
 'richsnob': 7317,
 '1910s': 5,
 'civilwar': 1688,
 'war': 9455,
 'fight': 3200,
 'navy': 5892,
 'mindreading': 5518,
 'hongkong': 4121,
 'soccer': 8090,
 'scientist': 7632,
 'fictionalwar': 3195,
 'naval': 5887,
 'armada': 386,
 'battleship': 724,
 'navalcombat': 5889,
 'jdsmyoko': 4561,
 'lostcommunication': 5081,
 'taser': 8702,
 'buoy': 1209,
 'communicationsexpert': 1839,
 'jointchiefsofstaff': 4616,
 'crashlanding': 2042,
 'jetfighterpilot': 4581,
 'navylieutenant': 5893,
 'permissiontomarry': 6439,
 'ussjohnpauljones': 9281,
 'basedonboardgame': 666,
 'mightymo': 5480,
 'ussmissouri': 9282,
 'dna': 2486,
 'tyrannosaurusrex': 9181,
 'velociraptor': 9318,
 'island': 4502,
 'suspense': 8590,
 'amusementpark': 240,
 'animalattack': 271,
 'themepark': 8849,
 'jurassicpark': 4654,
 'animalhorror': 274,
 'sociopath': 8115,
 'killer': 4712,
 'artgallery': 415,
 'istanbulturkey': 4511,
 'uzi': 9286,
 'boobytrap': 1013,
 'impersonatingapoliceofficer': 4301,
 'macao': 5141,
 'pizzaboy': 6570,
 'doctor': 2490,
 'tentacle': 8793,
 'death': 2264,
 'supervillain': 8557,
 'waronterror': 9474,
 'tennessee': 8786,
 'malibu': 5205,
 'tonystark': 8941,
 'ironman': 4495,
 'mandarin': 5221,
 'warmachine': 9468,
 'ironpatriot': 4496,
 'extremis': 2981,
 'queen': 6999,
 'fantasy': 3077,
 'aliceinwonderland': 152,
 'mutant': 5815,
 'beast': 740,
 'cyclops': 2172,
 'dormitory': 2537,
 'games': 3489,
 'bestfriend': 803,
 'university': 9243,
 'scary': 7595,
 'egypt': 2710,
 'sun': 8524,
 'chaos': 1510,
 'symbol': 8643,
 'artifact': 419,
 'transformers': 9033,
 'tank': 8689,
 'robot': 7360,
 'giantrobot': 3608,
 'transformingrobot': 9034,
 'circus': 1673,
 'hope': 4129,
 'illusion': 4277,
 'lost': 5075,
 'magictrick': 5173,
 'obsession': 6107,
 'electrocution': 2728,
 'medicalexperiment': 5364,
 'electricity': 2726,
 'artificialintelligence': 422,
 'computerprogram': 1859,
 'dystopia': 2664,
 'computer': 1853,
 'deception': 2298,
 'duel': 2638,
 'motorcycle': 5699,
 'neonlight': 5926,
 'autocracy': 525,
 'carrace': 1381,
 'comedy': 1812,
 'anthropomorphism': 307,
 'transformation': 9032,
 'alieninfection': 161,
 'magicalobject': 5168,
 'protector': 6904,
 'origin': 6219,
 'college': 1782,
 'toy': 8988,
 'barbie': 638,
 'daycare': 2229,
 'teddybear': 8735,
 'toycomestolife': 8989,
 'personification': 6448,
 'inanimateobjectscomingtolife': 4316,
 'toystory': 8994,
 'prophecy': 6892,
 'sanfrancisco': 7538,
 'cyborg': 2170,
 'killerrobot': 4717,
 'gasstation': 3525,
 'post': 6739,
 'apocalyptic': 331,
 'army': 397,
 'firearm': 3243,
 'wartime': 9484,
 'losangeles': 5044,
 'speed': 8219,
 'car': 1344,
 'race': 7010,
 'musclecar': 5778,
 'apocalypse': 330,
 'zombie': 9779,
 'nuclearweapons': 6076,
 'multipleperspectives': 5755,
 'zombieapocalypse': 9780,
 '1970s': 11,
 'storm': 8403,
 'changingthepastorfuture': 1507,
 'spacecraft': 8182,
 'friendship': 3431,
 'spaceopera': 8189,
 'terroristbombing': 8806,
 'giant': 3600,
 'infidelity': 4359,
 'persia': 6443,
 'brotheragainstbrother': 1156,
 'armageddon': 388,
 'regent': 7188,
 'basedonvideogame': 690,
 'giantmonster': 3606,
 'moon': 5650,
 'bodyguard': 985,
 'basedoncartoon': 667,
 'sabotage': 7482,
 'worddomination': 9678,
 'commando': 1828,
 'riddle': 7320,
 'whip': 9566,
 'treasure': 9070,
 'mexicocity': 5453,
 'leatherjacket': 4869,
 'machinegun': 5146,
 'alienphenomenons': 165,
 'mayacivilization': 5341,
 'peru': 6453,
 'treasurehunt': 9071,
 'nuclearexplosion': 6068,
 'refrigerator': 7182,
 'archaeologist': 360,
 'indianajones': 4329,
 'archeology': 365,
 'friends': 3430,
 'alternatehistory': 196,
 'fear': 3119,
 'nature': 5884,
 'human': 4189,
 'journey': 4622,
 'scotland': 7640,
 'rebel': 7106,
 'bravery': 1084,
 'kingdom': 4731,
 'wish': 9631,
 'bear': 735,
 'scot': 7639,
 'rebelliousdaughter': 7108,
 'turnsintoanimal': 9146,
 'archery': 367,
 'ruins': 7450,
 'peaceoffering': 6395,
 'womandirector': 9658,
 'courage': 2013,
 'stranded': 8416,
 'hatred': 3904,
 'romanticcomedy': 7401,
 'ambassador': 211,
 'civilization': 1683,
 'naturaldisaster': 5880,
 'endoftheworld': 2776,
 'volcaniceruption': 9408,
 'mayan': 5342,
 'ark': 383,
 'solar': 8123,
 'destructionofmankind': 2380,
 'holiday': 4079,
 'victorianengland': 9342,
 'money': 5621,
 'christmaseve': 1644,
 'scrooge': 7651,
 'christmascarol': 1643,
 'ghost': 3588,
 'lesson': 4898,
 'charlesdickens': 1523,
 'christmas': 1642,
 'jupiter': 4653,
 'interspeciesromance': 4439,
 'africa': 87,
 'feralchild': 3170,
 'tarzan': 8701,
 'jungle': 4644,
 'selfsacrifice': 7731,
 'winter': 9623,
 'cupboard': 2145,
 'beaver': 756,
 'fairy': 3011,
 'talefigure': 8663,
 'supernaturalpowers': 8549,
 'worlddomination': 9695,
 '1980s': 12,
 'scarecrow': 7593,
 'sadism': 7485,
 'joker': 4617,
 'organizedcrime': 6214,
 'criminalmastermind': 2078,
 'districtattorney': 2467,
 'agedifference': 96,
 'centralandsouthamerica': 1477,
 'balloon': 601,
 'floatingintheair': 3305,
 'exploring': 2959,
 'middleeast': 5472,
 'armsdealer': 395,
 'counterterrorism': 1998,
 'agentcoulson': 98,
 'library': 4927,
 'clock': 1729,
 'filmdirector': 3216,
 'key': 4698,
 'boy': 1060,
 'automaton': 527,
 'hiding': 4007,
 'legbrace': 4881,
 'doberman': 2487,
 'basedontvseries': 689,
 'steamlocomotive': 8350,
 'drag': 2556,
 'shareduniverse': 7842,
 'antihero': 313,
 'secretmission': 7700,
 'villain': 9374,
 'fathersonrelationship': 3110,
 'dailylife': 2180,
 'marriedcouple': 5280,
 'support': 8560,
 'father': 3104,
 'marriage': 5273,
 'baustelle': 725,
 'rescue': 7249,
 'noah': 6023,
 'sark': 7551,
 'dejavu': 2320,
 'timewarp': 8915,
 'restart': 7268,
 'militaryofficer': 5495,
 'exoskeleton': 2925,
 'tattoo': 8705,
 'water': 9495,
 'doomsday': 2528,
 'secret': 7684,
 'technology': 8734,
 'warhead': 9462,
 'government': 3712,
 'president': 6807,
 'murder': 5767,
 'attack': 482,
 'explosion': 2960,
 'lasers': 4820,
 'evil': 2875,
 'cobra': 1758,
 'dream': 2567,
 'cartoon': 1390,
 'imaginaryfriend': 4283,
 'family': 3045,
 'moving': 5740,
 'kids': 4709,
 'unicorn': 9234,
 'emotions': 2763,
 'snake': 8063,
 'wolf': 9649,
 'elephant': 2734,
 'tiger': 8900,
 'panther': 6300,
 'remake': 7220,
 'talkinganimal': 8671,
 'talkingtoanimals': 8676,
 'immortality': 4294,
 'forest': 3360,
 'woman': 9655,
 'eternalyouth': 2859,
 'snowwhite': 8086,
 'evilqueen': 2891,
 'evilstepmother': 2893,
 'imprisoned': 4311,
 'sorceress': 8147,
 'sleepingbeauty': 8022,
 'darkfantasy': 2217,
 'adaptation': 51,
 'retelling': 7277,
 'literaryadaptation': 4972,
 'leader': 4862,
 'colony': 1793,
 'woods': 9675,
 'ape': 328,
 'monkey': 5631,
 'medicalresearch': 5366,
 'plague': 6579,
 'japan': 4545,
 'suicide': 8508,
 'samurai': 7526,
 'basedontruestory': 688,
 'samuraisword': 7527,
 'ronin': 7407,
 'shogun': 7876,
 'halfbreed': 3851,
 'washingtond': 9490,
 'captainamerica': 1338,
 'politicalthriller': 6689,
 'ogre': 6132,
 'inventor': 4454,
 'destiny': 2374,
 'dreamer': 2568,
 'futuristiccar': 3464,
 'futuristiccity': 3465,
 'brotherbrotherrelationship': 1157,
 'hero': 3989,
 'talent': 8664,
 'anotherdimension': 299,
 'boygenius': 1068,
 'hate': 3902,
 'moraldilemma': 5661,
 'teensuperheroes': 8758,
 'deadbrother': 2245,
 'supportgroup': 8561,
 'productplacement': 6871,
 'bullying': 1203,
 'racing': 7021,
 'arcade': 358,
 'medal': 5355,
 'selfesteem': 7722,
 'curiosity': 2150,
 'precociouschild': 6782,
 'firstpersonshooter': 3265,
 'glitch': 3647,
 'carefree': 1361,
 'videogamer': 9349,
 'bert': 802,
 'interruptedwedding': 4437,
 'socialreject': 8107,
 'santaclaus': 7543,
 'nerd': 5928,
 'gift': 3616,
 'bell': 792,
 'beard': 737,
 'northpole': 6050,
 'chute': 1658,
 'trestle': 9080,
 'ticket': 8894,
 'flying': 3325,
 'blacksmith': 913,
 'arena': 375,
 'night': 6000,
 'training': 9020,
 'village': 9370,
 'viking': 9368,
 'ignorance': 4264,
 'flight': 3297,
 'nest': 5931,
 'combat': 1806,
 'well': 9545,
 'warrior': 9478,
 'manvsmachine': 5245,
 'sunglasses': 8526,
 'nanotechnology': 5849,
 'rocketlauncher': 7370,
 'firemen': 3253,
 'veterinarian': 9334,
 'fireengine': 3248,
 'psychiatrist': 6923,
 'spaceship': 8193,
 'outerspace': 6238,
 'adventurer': 74,
 'singleparent': 7971,
 'nasa': 5864,
 'expedition': 2933,
 'wormhole': 9705,
 'famine': 3064,
 'blackhole': 898,
 'raceagainsttime': 7012,
 'quantummechanics': 6993,
 'familyrelationships': 3060,
 'farmhouse': 3084,
 'astronaut': 466,
 'fatherdaughterrelationship': 3105,
 'singlefather': 7969,
 'farmer': 3083,
 'spacestation': 8194,
 'astrophysics': 469,
 'zerogravity': 9776,
 'timeparadox': 8910,
 'relativity': 7201,
 'lossoflover': 5064,
 'kidnapping': 4707,
 'sleep': 8019,
 'subconsciousness': 8478,
 'heist': 3962,
 'redemption': 7141,
 'femalehero': 3144,
 'godzilla': 3669,
 'kaiju': 4667,
 'toyko': 8990,
 'mountains': 5718,
 'ring': 7332,
 'goblin': 3662,
 'tunnel': 9135,
 'undergroundlake': 9212,
 'buriedtreasure': 1217,
 'climbingatree': 1725,
 'invisibility': 4462,
 'ancient': 249,
 'gnomes': 3656,
 'streetgang': 8434,
 'auto': 521,
 'tuning': 9134,
 'automobileracing': 529,
 'diary': 2404,
 'funeral': 3449,
 'tea': 8717,
 'travel': 9062,
 'hospital': 4149,
 'cia': 1659,
 'mine': 5521,
 'historicalfiction': 4049,
 'nuclearwar': 6074,
 'cubanmissilecrisis': 2129,
 'worldwariii': 9704,
 '1960s': 10,
 'revolution': 7301,
 'gameofdeath': 3488,
 'fire': 3242,
 'fountain': 3380,
 'book': 1015,
 'castle': 1412,
 'apprentice': 346,
 'merlin': 5422,
 'mission': 5575,
 'sorcerer': 8146,
 'apprendista': 345,
 'morgana': 5664,
 'newyear': 5984,
 'seve': 7770,
 'drowning': 2591,
 'cataclysm': 1418,
 'atlanticocean': 476,
 'ball': 597,
 'self': 7720,
 'abandonment': 24,
 'giantwave': 3612,
 'blackout': 907,
 'single': 7968,
 'capsizedship': 1336,
 'madhatter': 5155,
 'ambush': 217,
 'sadness': 7490,
 'stage': 8306,
 'liberationofprisoners': 4924,
 'prince': 6833,
 'donkey': 2524,
 'theatreplay': 8835,
 'conciliation': 1874,
 'tricks': 9088,
 'heirtothethrone': 3961,
 'assault': 455,
 'boardingschool': 970,
 'coupd': 2010,
 'etat': 2857,
 'teacher': 8718,
 'cowardliness': 2031,
 'pregnancy': 6787,
 'capture': 1342,
 'videogame': 9348,
 'chase': 1527,
 'fictionallanguage': 3192,
 'muscles': 5780,
 'orc': 6203,
 'fiction': 3185,
 'goodvsevil': 3697,
 'king': 4729,
 'knifeheldtothroat': 4745,
 'snowing': 8081,
 'quest': 7003,
 'nurse': 6090,
 'patriotism': 6386,
 'hawaii': 3912,
 'worldwarii': 9703,
 'pilot': 6536,
 'pearlharbor': 6397,
 'airforce': 113,
 'airplane': 119,
 'pin': 6540,
 'destroy': 2375,
 'basedontoy': 686,
 'teenagehero': 8740,
 'aristotle': 381,
 'greece': 3749,
 'campaign': 1296,
 'alexanderthegreat': 148,
 'homosexuality': 4117,
 'gayrelationship': 3535,
 'ancientworld': 258,
 'cuttingthecord': 2163,
 'childhero': 1579,
 'dyinganddeath': 2655,
 'sapprentice': 7547,
 'blackmagic': 902,
 'sorcery': 8148,
 'occultism': 6111,
 'chosenone': 1637,
 'tournament': 8977,
 'teenager': 8746,
 'alcohol': 142,
 'forbiddenlove': 3347,
 'lovers': 5108,
 'affection': 85,
 'advertisingexpert': 78,
 'alcoholism': 147,
 'pokies': 6631,
 'lostcivilisation': 5080,
 'alone': 188,
 'helplessness': 3977,
 'virus': 9395,
 'pandemic': 6297,
 'londonengland': 5019,
 'chocolate': 1628,
 'factoryworker': 3003,
 'parentskidsrelationship': 6337,
 'candy': 1318,
 'overweightchild': 6258,
 'grandfathergrandsonrelationship': 3725,
 'paris': 6338,
 'expensiverestaurant': 2934,
 'river': 7346,
 'cook': 1950,
 'mouse': 5725,
 'confidence': 1890,
 'roof': 7408,
 'window': 9612,
 'leavingone': 4872,
 'sfamily': 7825,
 'work': 9679,
 'restaurantcritic': 7271,
 'kitchen': 4737,
 'spice': 8234,
 'court': 2014,
 'cookbook': 1951,
 'chef': 1550,
 'rat': 7082,
 'himalaya': 4036,
 'martialarts': 5287,
 'rivalry': 7345,
 'ninja': 6018,
 'crime': 2061,
 'hauntedbythepast': 3907,
 'evildoctor': 2884,
 'escapade': 2835,
 'mastervillain': 5325,
 'fightingcrime': 3206,
 'unfulfillment': 9232,
 'loveandromance': 5097,
 'unfulfilledlove': 9231,
 'jealousy': 4563,
 'dance': 2191,
 'hunger': 4213,
 'zoo': 9782,
 'hippopotamus': 4044,
 'chimp': 1611,
 'penguin': 6416,
 'volcano': 9409,
 'madagascar': 5151,
 'zebra': 9774,
 'shark': 7843,
 'museum': 5783,
 'theodoreroosevelt': 8851,
 'ameliaearhart': 218,
 'smithsonian': 8048,
 'boxer': 1053,
 'philosophy': 6488,
 'kungfu': 4771,
 'undergroundworld': 9213,
 'temple': 8781,
 'subway': 8494,
 'sunlight': 8528,
 'computervirus': 1862,
 'precognition': 6784,
 'supercomputer': 8533,
 'machinetown': 5147,
 'yingyang': 9747,
 'virtualreality': 9394,
 'worldreligion': 9699,
 'truth': 9124,
 'cyberpunk': 2166,
 'yinyang': 9748,
 'gnosticism': 3657,
 'betrayal': 811,
 'snowman': 8083,
 'reindeer': 7194,
 'curse': 2153,
 'snow': 8077,
 'troll': 9097,
 'mountainclimber': 5713,
 'plato': 6598,
 'rave': 7085,
 'hostiletakeover': 4159,
 'norsemythology': 6041,
 'asgard': 437,
 'australia': 510,
 'survival': 8581,
 'ontherun': 6185,
 'convoy': 1949,
 'peakoil': 6396,
 'darkfuture': 2218,
 'rome': 7404,
 'vatican': 9308,
 'symbolism': 8644,
 'christian': 1639,
 'illuminati': 4276,
 'prequel': 6804,
 'antimatter': 314,
 'conspiracy': 1916,
 'investigator': 4458,
 'catholicism': 1433,
 'cern': 1482,
 'newmexico': 5960,
 'banishment': 617,
 'hammer': 3863,
 'odin': 6122,
 'heimdall': 3957,
 'hamster': 3866,
 'kidsandfamily': 4710,
 'catvsdog': 1445,
 'dogcatfriendship': 2501,
 'animallead': 277,
 'girldogrelationship': 3626,
 'dyr': 2660,
 'underworld': 9220,
 'hades': 3839,
 'mythology': 5837,
 'greekmythology': 3756,
 'zeus': 9777,
 'perseus': 6442,
 'gods': 3668,
 'ancientgreece': 255,
 'basedongreekmyth': 675,
 'ares': 376,
 'imprisonment': 4312,
 'vampire': 9295,
 'fishoutofwater': 3273,
 'chains': 1489,
 'gothic': 3707,
 'madness': 5158,
 'oldhouse': 6153,
 'lostlove': 5083,
 'angrymob': 268,
 '18thcentury': 4,
 'hiddenroom': 4003,
 'oldmansion': 6155,
 'austria': 515,
 'viennaopera': 9358,
 'vienna': 9356,
 'ruralsetting': 7465,
 'tennis': 8787,
 'flower': 3317,
 'florist': 3316,
 'flowershop': 3320,
 'beehive': 768,
 'fleet': 3294,
 'panda': 6296,
 'ice': 4241,
 'warship': 9482,
 'arrest': 404,
 'avatar': 538,
 'air': 108,
 'spirit': 8244,
 'world': 9692,
 'domination': 2519,
 'cheering': 1544,
 'berlin': 800,
 'whitehouse': 9577,
 'explosive': 2961,
 'mobilephone': 5596,
 'map': 5249,
 'mask': 5302,
 'honeymoon': 4119,
 'shanghai': 7838,
 'pretendedmurder': 6817,
 'letter': 4902,
 'coveredinvestigation': 2025,
 'toshootdead': 8961,
 'video': 9344,
 'stamp': 8322,
 'harddrive': 3886,
 'mail': 5182,
 'decipherment': 2299,
 'suitcase': 8514,
 'disguise': 2452,
 'celebration': 1460,
 'goodandbad': 3692,
 'researchlaboratory': 7256,
 'blast': 918,
 'usapresident': 9277,
 'secretservice': 7705,
 'thewhitehouse': 8866,
 'alienabduction': 154,
 'basedonchildren': 668,
 'sbook': 7581,
 'return': 7286,
 'frog': 3438,
 'girlfriend': 3628,
 'rubin': 7446,
 'peterpan': 6466,
 'intelligence': 4412,
 'adoption': 62,
 'childprodigy': 1599,
 'growingup': 3793,
 'children': 1602,
 'talkingdog': 8673,
 'dog': 2498,
 'firstlove': 3264,
 'ancientegypt': 253,
 'timetraveler': 8914,
 'newschool': 5965,
 'georgewashington': 3564,
 'gags': 3469,
 'trouble': 9102,
 'prodigy': 6868,
 'adultery': 69,
 'beauty': 750,
 'trojanwar': 9096,
 'wall': 9444,
 'fraud': 3401,
 'swordfight': 8638,
 'battlefield': 717,
 'pyre': 6991,
 'trojanhorse': 9095,
 'trojan': 9094,
 'bronzeage': 1148,
 'spartagreece': 8206,
 'helenoftroy': 3968,

In [57]:
# 넘파이 배열로 표현하기 - 등장한 단어 개수 카운팅
genre_mat.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4803, 9789))

In [58]:
# 배열을 데이터프레임으로 만들기, 
df_genre_vec = pd.DataFrame(genre_mat.toarray())
df_genre_vec.columns = sorted(count_vec.vocabulary_, key=count_vec.vocabulary_.get) # 단어의 순서대로 열에 적용한다.
df_genre_vec.index = df["title"]
df_genre_vec.head()

,11,15thcentury,16thcentury,17thcentury,18thcentury,1910s,1920s,1930s,1940s,1950s,...,zombie,zombieapocalypse,zombification,zoo,zookeeper,zurich,γη,卧底肥妈,绝地奶霸,超级妈妈
title,,,,,,,,,,,,,,,,,,,,,
Avatar,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Pirates of the Caribbean: At World's End,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Spectre,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
The Dark Knight Rises,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
John Carter,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [59]:
from sklearn.metrics.pairwise import cosine_similarity

genre_sim = cosine_similarity(df_genre_vec, df_genre_vec)   # 코사인 유사도로 비교한다.
genre_sim

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(4803, 4803))

In [60]:
genre_sim_df = pd.DataFrame(genre_sim)      # 유사도 표를 데이터프레임으로 만들어서 볼 수 있게 한다.
genre_sim_df.columns = df["title"]          # 영화 제목이 행과 열이기 때문
genre_sim_df.index = df["title"]
genre_sim_df

title,Avatar,Pirates of the Caribbean: At World's End,Spectre,The Dark Knight Rises,John Carter,Spider-Man 3,Tangled,Avengers: Age of Ultron,Harry Potter and the Half-Blood Prince,Batman v Superman: Dawn of Justice,...,On The Downlow,Sanctuary: Quite a Conundrum,Bang,Primer,Cavite,El Mariachi,Newlyweds,"Signed, Sealed, Delivered",Shanghai Calling,My Date with Drew
title,,,,,,,,,,,,,,,,,,,,,
Avatar,1.000000,0.0,0.000000,0.0,0.163663,0.000000,0.00000,0.072739,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Pirates of the Caribbean: At World's End,0.000000,1.0,0.000000,0.0,0.000000,0.117647,0.00000,0.000000,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Spectre,0.000000,0.0,1.000000,0.0,0.094491,0.091670,0.00000,0.125988,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
The Dark Knight Rises,0.000000,0.0,0.000000,1.0,0.000000,0.051709,0.00000,0.071067,0.0,0.213201,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
John Carter,0.163663,0.0,0.094491,0.0,1.000000,0.000000,0.06455,0.083333,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
El Mariachi,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
Newlyweds,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"Signed, Sealed, Delivered",0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
Shanghai Calling,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
My Date with Drew,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [61]:
genre_sim_df.iloc[0].sort_values(ascending=False) # 0번째 행에 있는 영화제목과 유사도값들을 내림차순으로 불러옴

title
Avatar                       1.000000
Star Trek Into Darkness      0.276026
A Monster in Paris           0.218218
Top Cat Begins               0.218218
Jupiter Ascending            0.195180
                               ...
El Mariachi                  0.000000
Newlyweds                    0.000000
Signed, Sealed, Delivered    0.000000
Shanghai Calling             0.000000
Spectre                      0.000000
Name: Avatar, Length: 4803, dtype: float64

In [62]:
query = "Superman II"

index_no = df.loc[df["title"]==query,:].index[0]    # 쿼리를 만들어서 이런식으로 함수화가 가능함.

genre_sim_df.iloc[index_no].sort_values(ascending=False)

title
Superman II                  1.000000
Superman Returns             0.613941
Superman III                 0.585369
Superman                     0.470871
Man of Steel                 0.462250
                               ...
El Mariachi                  0.000000
Newlyweds                    0.000000
Signed, Sealed, Delivered    0.000000
Shanghai Calling             0.000000
She Wore a Yellow Ribbon     0.000000
Name: Superman II, Length: 4803, dtype: float64